export const cusines_types = [
  "American",
  "Asian",
  "British",
  "Caribbean",
  "Europe",
  "Chinese",
  "French",
  "Indian",
  "Italian",
  "Japanese",
  "Kosher",
  "Mediterranean",
  "Mexican",
  "Middle Eastern",
  "Nordic",
  "South American",
  "South East Asian",
];
