export const DISHES_LOADING = "DISHES_LOADING";
export const DISHES_FAILED = "DISHES_FAILES";
export const ADD_DISHES = "ADD_DISHES";
export const SEARCHED_DISHES_LOADING = "SEARCHED_DISHES_LOADING";
export const SEARCHED_DISHES_FAILED = "SEARCHED_DISHES_FAILED";
export const ADD_SEARCHED_DISHES = "ADD_SEARCHED_DISHES";
